In [1]:
import pandas as pd
df=pd.read_csv(r"C:\Users\user\Downloads\Students Social Media Addiction.csv")
df

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8
1,2,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3
2,3,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9
3,4,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4
4,5,21,Male,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
700,701,20,Female,Undergraduate,Italy,4.7,TikTok,No,7.2,7,In Relationship,2,5
701,702,23,Male,Graduate,Russia,6.8,Instagram,Yes,5.9,4,Single,5,9
702,703,21,Female,Undergraduate,China,5.6,WeChat,Yes,6.7,6,In Relationship,3,7
703,704,24,Male,Graduate,Japan,4.3,Twitter,No,7.5,8,Single,2,4
704,705,19,Female,Undergraduate,Poland,6.2,Facebook,Yes,6.3,5,Single,4,8

In [3]:
df.head()

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8
1,2,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3
2,3,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9
3,4,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4
4,5,21,Male,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7

In [4]:
students = df.to_dict(orient="records")

In [5]:
len(students)

705

In [6]:
def view_students():
    if len(students) == 0:
        print("No student records available.")
    else:
        for i, student in enumerate(students, start=1):
            print(f"\nStudent {i}")
            for key, value in student.items():
                print(key, ":", value)

In [7]:
view_students()

Student 1
Student_ID : 1
Age : 19
Gender : Female
Academic_Level : Undergraduate
Country : Bangladesh
Avg_Daily_Usage_Hours : 5.2
Most_Used_Platform : Instagram
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 6.5
Mental_Health_Score : 6
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 3
Addicted_Score : 8

Student 2
Student_ID : 2
Age : 22
Gender : Male
Academic_Level : Graduate
Country : India
Avg_Daily_Usage_Hours : 2.1
Most_Used_Platform : Twitter
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 7.5
Mental_Health_Score : 8
Relationship_Status : Single
Conflicts_Over_Social_Media : 0
Addicted_Score : 3

Student 3
Student_ID : 3
Age : 20
Gender : Female
Academic_Level : Undergraduate
Country : USA
Avg_Daily_Usage_Hours : 6.0
Most_Used_Platform : TikTok
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.0
Mental_Health_Score : 5
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 4
Addicted_Score : 9

Student 4
Student_ID : 4
Age : 18
Gender : Male
Academic_Level : High School
Country : UK
Avg_Daily_Usage_Hours : 3.0
Most_Used_Platform : YouTube
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 7.0
Mental_Health_Score : 7
Relationship_Status : Single
Conflicts_Over_Social_Media : 1
Addicted_Score : 4

Student 5
Student_ID : 5
Age : 21
Gender : Male
Academic_Level : Graduate
Country : Canada
Avg_Daily_Usage_Hours : 4.5
Most_Used_Platform : Facebook
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 6.0
Mental_Health_Score : 6
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 2
Addicted_Score : 7

Student 6
Student_ID : 6
Age : 19
Gender : Female
Academic_Level : Undergraduate
Country : Australia
Avg_Daily_Usage_Hours : 7.2
Most_Used_Platform : Instagram
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 4.5
Mental_Health_Score : 4
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 5
Addicted_Score : 9

Student 7
Student_ID : 7
Age : 23
Gender : Male
Academic_Level : Graduate
Country : Germany
Avg_Daily_Usage_Hours : 1.5
Most_Used_Platform : LinkedIn
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 8.0
Mental_Health_Score : 9
Relationship_Status : Single
Conflicts_Over_Social_Media : 0
Addicted_Score : 2

Student 8
Student_ID : 8
Age : 20
Gender : Female
Academic_Level : Undergraduate
Country : Brazil
Avg_Daily_Usage_Hours : 5.8
Most_Used_Platform : Snapchat
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 6.0
Mental_Health_Score : 6
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 2
Addicted_Score : 8

Student 9
Student_ID : 9
Age : 18
Gender : Male
Academic_Level : High School
Country : Japan
Avg_Daily_Usage_Hours : 4.0
Most_Used_Platform : TikTok
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 6.5
Mental_Health_Score : 7
Relationship_Status : Single
Conflicts_Over_Social_Media : 1
Addicted_Score : 5

Student 10
Student_ID : 10
Age : 21
Gender : Female
Academic_Level : Graduate
Country : South Korea
Avg_Daily_Usage_Hours : 3.3
Most_Used_Platform : Instagram
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 7.0
Mental_Health_Score : 7
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 1
Addicted_Score : 4

Student 11
Student_ID : 11
Age : 19
Gender : Male
Academic_Level : Undergraduate
Country : France
Avg_Daily_Usage_Hours : 4.8
Most_Used_Platform : Snapchat
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 6.2
Mental_Health_Score : 5
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 3
Addicted_Score : 7

Student 12
Student_ID : 12
Age : 20
Gender : Female
Academic_Level : Undergraduate
Country : Spain
Avg_Daily_Usage_Hours : 5.5
Most_Used_Platform : TikTok
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.8
Mental_Health_Score : 6
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 2
Addicted_Score : 8

Student 13
Student_ID : 13
Age : 22
Gender : Male
Academic_Level : Graduate
Country : Italy
Avg_Daily_Usage_Hours : 2.8
Most_Used_Platform : LinkedIn
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 7.2
Mental_Health_Score : 8
Relationship_Status : Single
Conflicts_Over_Social_Media : 1
Addicted_Score : 4

Student 14
Student_ID : 14
Age : 18
Gender : Female
Academic_Level : High School
Country : Mexico
Avg_Daily_Usage_Hours : 6.5
Most_Used_Platform : Instagram
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.5
Mental_Health_Score : 5
Relationship_Status : Single
Conflicts_Over_Social_Media : 4
Addicted_Score : 9

Student 15
Student_ID : 15
Age : 21
Gender : Male
Academic_Level : Undergraduate
Country : Russia
Avg_Daily_Usage_Hours : 3.7
Most_Used_Platform : YouTube
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 6.8
Mental_Health_Score : 7
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 2
Addicted_Score : 5

Student 16
Student_ID : 16
Age : 20
Gender : Female
Academic_Level : Undergraduate
Country : China
Avg_Daily_Usage_Hours : 4.2
Most_Used_Platform : TikTok
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 6.0
Mental_Health_Score : 6
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 3
Addicted_Score : 7

Student 17
Student_ID : 17
Age : 24
Gender : Male
Academic_Level : Graduate
Country : Sweden
Avg_Daily_Usage_Hours : 2.0
Most_Used_Platform : LinkedIn
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 7.8
Mental_Health_Score : 8
Relationship_Status : Single
Conflicts_Over_Social_Media : 0
Addicted_Score : 3

Student 18
Student_ID : 18
Age : 19
Gender : Female
Academic_Level : High School
Country : Norway
Avg_Daily_Usage_Hours : 5.0
Most_Used_Platform : Instagram
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.7
Mental_Health_Score : 5
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 3
Addicted_Score : 8

Student 19
Student_ID : 19
Age : 21
Gender : Male
Academic_Level : Undergraduate
Country : Denmark
Avg_Daily_Usage_Hours : 3.5
Most_Used_Platform : Facebook
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 6.7
Mental_Health_Score : 7
Relationship_Status : Single
Conflicts_Over_Social_Media : 1
Addicted_Score : 5

Student 20
Student_ID : 20
Age : 20
Gender : Female
Academic_Level : Undergraduate
Country : Netherlands
Avg_Daily_Usage_Hours : 4.7
Most_Used_Platform : Snapchat
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.9
Mental_Health_Score : 6
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 3
Addicted_Score : 7

Student 21
Student_ID : 21
Age : 18
Gender : Male
Academic_Level : High School
Country : Belgium
Avg_Daily_Usage_Hours : 5.3
Most_Used_Platform : TikTok
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.5
Mental_Health_Score : 5
Relationship_Status : Single
Conflicts_Over_Social_Media : 4
Addicted_Score : 8

Student 22
Student_ID : 22
Age : 23
Gender : Female
Academic_Level : Graduate
Country : Switzerland
Avg_Daily_Usage_Hours : 2.5
Most_Used_Platform : LinkedIn
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 7.3
Mental_Health_Score : 8
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 1
Addicted_Score : 4

Student 23
Student_ID : 23
Age : 19
Gender : Male
Academic_Level : Undergraduate
Country : Austria
Avg_Daily_Usage_Hours : 4.9
Most_Used_Platform : Instagram
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.8
Mental_Health_Score : 6
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 3
Addicted_Score : 7

Student 24
Student_ID : 24
Age : 20
Gender : Female
Academic_Level : Undergraduate
Country : Portugal
Avg_Daily_Usage_Hours : 5.7
Most_Used_Platform : TikTok
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.4
Mental_Health_Score : 5
Relationship_Status : Single
Conflicts_Over_Social_Media : 4
Addicted_Score : 8

Student 25
Student_ID : 25
Age : 22
Gender : Male
Academic_Level : Graduate
Country : Greece
Avg_Daily_Usage_Hours : 3.2
Most_Used_Platform : Facebook
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 6.9
Mental_Health_Score : 7
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 2
Addicted_Score : 5

Student 26
Student_ID : 26
Age : 19
Gender : Female
Academic_Level : High School
Country : Ireland
Avg_Daily_Usage_Hours : 6.1
Most_Used_Platform : Instagram
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.2
Mental_Health_Score : 5
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 4
Addicted_Score : 9

Student 27
Student_ID : 27
Age : 21
Gender : Male
Academic_Level : Undergraduate
Country : New Zealand
Avg_Daily_Usage_Hours : 3.8
Most_Used_Platform : YouTube
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 6.6
Mental_Health_Score : 7
Relationship_Status : Single
Conflicts_Over_Social_Media : 1
Addicted_Score : 5

Student 28
Student_ID : 28
Age : 20
Gender : Female
Academic_Level : Undergraduate
Country : Singapore
Avg_Daily_Usage_Hours : 4.4
Most_Used_Platform : TikTok
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.9
Mental_Health_Score : 6
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 3
Addicted_Score : 7

Student 29
Student_ID : 29
Age : 24
Gender : Male
Academic_Level : Graduate
Country : Malaysia
Avg_Daily_Usage_Hours : 2.2
Most_Used_Platform : LinkedIn
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 7.4
Mental_Health_Score : 8
Relationship_Status : Single
Conflicts_Over_Social_Media : 0
Addicted_Score : 3

Student 30
Student_ID : 30
Age : 19
Gender : Female
Academic_Level : High School
Country : Thailand
Avg_Daily_Usage_Hours : 5.9
Most_Used_Platform : Instagram
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.3
Mental_Health_Score : 5
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 4
Addicted_Score : 8

Student 31
Student_ID : 31
Age : 21
Gender : Male
Academic_Level : Undergraduate
Country : Vietnam
Avg_Daily_Usage_Hours : 3.6
Most_Used_Platform : Facebook
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 6.7
Mental_Health_Score : 7
Relationship_Status : Single
Conflicts_Over_Social_Media : 1
Addicted_Score : 5

Student 32
Student_ID : 32
Age : 20
Gender : Female
Academic_Level : Undergraduate
Country : Philippines
Avg_Daily_Usage_Hours : 4.8
Most_Used_Platform : Snapchat
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.7
Mental_Health_Score : 6
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 3
Addicted_Score : 7

Student 33
Student_ID : 33
Age : 18
Gender : Male
Academic_Level : High School
Country : Indonesia
Avg_Daily_Usage_Hours : 5.4
Most_Used_Platform : TikTok
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.4
Mental_Health_Score : 5
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 4
Addicted_Score : 8

Student 34
Student_ID : 34
Age : 23
Gender : Female
Academic_Level : Graduate
Country : Taiwan
Avg_Daily_Usage_Hours : 2.6
Most_Used_Platform : LinkedIn
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 7.2
Mental_Health_Score : 8
Relationship_Status : Single
Conflicts_Over_Social_Media : 1
Addicted_Score : 4

Student 35
Student_ID : 35
Age : 19
Gender : Male
Academic_Level : Undergraduate
Country : Hong Kong
Avg_Daily_Usage_Hours : 4.7
Most_Used_Platform : Instagram
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.8
Mental_Health_Score : 6
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 3
Addicted_Score : 7

Student 36
Student_ID : 36
Age : 20
Gender : Female
Academic_Level : Undergraduate
Country : Turkey
Avg_Daily_Usage_Hours : 5.6
Most_Used_Platform : TikTok
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.5
Mental_Health_Score : 5
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 4
Addicted_Score : 8

Student 37
Student_ID : 37
Age : 22
Gender : Male
Academic_Level : Graduate
Country : Israel
Avg_Daily_Usage_Hours : 3.1
Most_Used_Platform : Facebook
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 6.8
Mental_Health_Score : 7
Relationship_Status : Single
Conflicts_Over_Social_Media : 1
Addicted_Score : 5

Student 38
Student_ID : 38
Age : 19
Gender : Female
Academic_Level : High School
Country : UAE
Avg_Daily_Usage_Hours : 6.2
Most_Used_Platform : Instagram
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.1
Mental_Health_Score : 5
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 4
Addicted_Score : 9

Student 39
Student_ID : 39
Age : 21
Gender : Male
Academic_Level : Undergraduate
Country : Egypt
Avg_Daily_Usage_Hours : 3.9
Most_Used_Platform : YouTube
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 6.5
Mental_Health_Score : 7
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 2
Addicted_Score : 6

Student 40
Student_ID : 40
Age : 20
Gender : Female
Academic_Level : Undergraduate
Country : Morocco
Avg_Daily_Usage_Hours : 4.5
Most_Used_Platform : TikTok
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.8
Mental_Health_Score : 6
Relationship_Status : Single
Conflicts_Over_Social_Media : 3
Addicted_Score : 7

Student 41
Student_ID : 41
Age : 24
Gender : Male
Academic_Level : Graduate
Country : South Africa
Avg_Daily_Usage_Hours : 2.3
Most_Used_Platform : LinkedIn
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 7.3
Mental_Health_Score : 8
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 1
Addicted_Score : 4

Student 42
Student_ID : 42
Age : 19
Gender : Female
Academic_Level : High School
Country : Nigeria
Avg_Daily_Usage_Hours : 5.8
Most_Used_Platform : Instagram
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.4
Mental_Health_Score : 5
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 4
Addicted_Score : 8

Student 43
Student_ID : 43
Age : 21
Gender : Male
Academic_Level : Undergraduate
Country : Kenya
Avg_Daily_Usage_Hours : 3.7
Most_Used_Platform : Facebook
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 6.6
Mental_Health_Score : 7
Relationship_Status : Single
Conflicts_Over_Social_Media : 2
Addicted_Score : 5

Student 44
Student_ID : 44
Age : 20
Gender : Female
Academic_Level : Undergraduate
Country : Ghana
Avg_Daily_Usage_Hours : 4.6
Most_Used_Platform : Snapchat
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.7
Mental_Health_Score : 6
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 3
Addicted_Score : 7

Student 45
Student_ID : 45
Age : 18
Gender : Male
Academic_Level : High School
Country : Argentina
Avg_Daily_Usage_Hours : 5.5
Most_Used_Platform : TikTok
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.3
Mental_Health_Score : 5
Relationship_Status : Single
Conflicts_Over_Social_Media : 4
Addicted_Score : 8

Student 46
Student_ID : 46
Age : 23
Gender : Female
Academic_Level : Graduate
Country : Chile
Avg_Daily_Usage_Hours : 2.7
Most_Used_Platform : LinkedIn
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 7.1
Mental_Health_Score : 8
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 1
Addicted_Score : 4

Student 47
Student_ID : 47
Age : 19
Gender : Male
Academic_Level : Undergraduate
Country : Colombia
Avg_Daily_Usage_Hours : 4.8
Most_Used_Platform : Instagram
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.9
Mental_Health_Score : 6
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 3
Addicted_Score : 7

Student 48
Student_ID : 48
Age : 20
Gender : Female
Academic_Level : Undergraduate
Country : Peru
Avg_Daily_Usage_Hours : 5.5
Most_Used_Platform : TikTok
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.6
Mental_Health_Score : 5
Relationship_Status : Single
Conflicts_Over_Social_Media : 4
Addicted_Score : 8

Student 49
Student_ID : 49
Age : 22
Gender : Male
Academic_Level : Graduate
Country : Venezuela
Avg_Daily_Usage_Hours : 3.3
Most_Used_Platform : Facebook
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 6.7
Mental_Health_Score : 7
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 2
Addicted_Score : 5

Student 50
Student_ID : 50
Age : 19
Gender : Female
Academic_Level : High School
Country : Ecuador
Avg_Daily_Usage_Hours : 6.3
Most_Used_Platform : Instagram
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.2
Mental_Health_Score : 5
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 4
Addicted_Score : 9

Student 51
Student_ID : 51
Age : 21
Gender : Male
Academic_Level : Undergraduate
Country : Uruguay
Avg_Daily_Usage_Hours : 3.8
Most_Used_Platform : YouTube
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 6.4
Mental_Health_Score : 7
Relationship_Status : Single
Conflicts_Over_Social_Media : 2
Addicted_Score : 6

Student 52
Student_ID : 52
Age : 20
Gender : Female
Academic_Level : Undergraduate
Country : Paraguay
Avg_Daily_Usage_Hours : 4.7
Most_Used_Platform : TikTok
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.8
Mental_Health_Score : 6
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 3
Addicted_Score : 7

Student 53
Student_ID : 53
Age : 24
Gender : Male
Academic_Level : Graduate
Country : Bolivia
Avg_Daily_Usage_Hours : 2.4
Most_Used_Platform : LinkedIn
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 7.2
Mental_Health_Score : 8
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 1
Addicted_Score : 4

Student 54
Student_ID : 54
Age : 19
Gender : Female
Academic_Level : High School
Country : Costa Rica
Avg_Daily_Usage_Hours : 5.7
Most_Used_Platform : Instagram
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.5
Mental_Health_Score : 5
Relationship_Status : Single
Conflicts_Over_Social_Media : 4
Addicted_Score : 8

Student 55
Student_ID : 55
Age : 21
Gender : Male
Academic_Level : Undergraduate
Country : Panama
Avg_Daily_Usage_Hours : 3.6
Most_Used_Platform : Facebook
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 6.5
Mental_Health_Score : 7
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 2
Addicted_Score : 5

Student 56
Student_ID : 56
Age : 20
Gender : Female
Academic_Level : Undergraduate
Country : Jamaica
Avg_Daily_Usage_Hours : 4.9
Most_Used_Platform : Snapchat
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.6
Mental_Health_Score : 6
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 3
Addicted_Score : 7

Student 57
Student_ID : 57
Age : 18
Gender : Male
Academic_Level : High School
Country : Trinidad
Avg_Daily_Usage_Hours : 5.6
Most_Used_Platform : TikTok
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.2
Mental_Health_Score : 5
Relationship_Status : Single
Conflicts_Over_Social_Media : 4
Addicted_Score : 8

Student 58
Student_ID : 58
Age : 23
Gender : Female
Academic_Level : Graduate
Country : Bahamas
Avg_Daily_Usage_Hours : 2.8
Most_Used_Platform : LinkedIn
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 7.0
Mental_Health_Score : 8
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 1
Addicted_Score : 4

Student 59
Student_ID : 59
Age : 19
Gender : Male
Academic_Level : Undergraduate
Country : Iceland
Avg_Daily_Usage_Hours : 4.6
Most_Used_Platform : Instagram
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.9
Mental_Health_Score : 6
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 3
Addicted_Score : 7

Student 60
Student_ID : 60
Age : 20
Gender : Female
Academic_Level : Undergraduate
Country : Finland
Avg_Daily_Usage_Hours : 5.4
Most_Used_Platform : TikTok
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.7
Mental_Health_Score : 5
Relationship_Status : Single
Conflicts_Over_Social_Media : 4
Addicted_Score : 8

Student 61
Student_ID : 61
Age : 22
Gender : Male
Academic_Level : Graduate
Country : Poland
Avg_Daily_Usage_Hours : 3.1
Most_Used_Platform : Facebook
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 7.1
Mental_Health_Score : 7
Relationship_Status : Single
Conflicts_Over_Social_Media : 1
Addicted_Score : 5

Student 62

In [8]:
def search_by_gender():
    gender = input("Enter gender to search: ").strip().title()
    found = False

    for student in students:
        if student.get("Gender") == gender:
            print(student)
            found = True

    if not found:
        print("No matching records found.")

In [10]:
search_by_gender()

Enter gender to search:  Male

{'Student_ID': 2, 'Age': 22, 'Gender': 'Male', 'Academic_Level': 'Graduate', 'Country': 'India', 'Avg_Daily_Usage_Hours': 2.1, 'Most_Used_Platform': 'Twitter', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 7.5, 'Mental_Health_Score': 8, 'Relationship_Status': 'Single', 'Conflicts_Over_Social_Media': 0, 'Addicted_Score': 3}
{'Student_ID': 4, 'Age': 18, 'Gender': 'Male', 'Academic_Level': 'High School', 'Country': 'UK', 'Avg_Daily_Usage_Hours': 3.0, 'Most_Used_Platform': 'YouTube', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 7.0, 'Mental_Health_Score': 7, 'Relationship_Status': 'Single', 'Conflicts_Over_Social_Media': 1, 'Addicted_Score': 4}
{'Student_ID': 5, 'Age': 21, 'Gender': 'Male', 'Academic_Level': 'Graduate', 'Country': 'Canada', 'Avg_Daily_Usage_Hours': 4.5, 'Most_Used_Platform': 'Facebook', 'Affects_Academic_Performance': 'Yes', 'Sleep_Hours_Per_Night': 6.0, 'Mental_Health_Score': 6, 'Relationship_Status': 'In Relationship', 'Conflicts_Over_Social_Media': 2, 'Addicted_Score': 7}
{'Student_ID': 7, 'Age': 23, 'Gender': 'Male', 'Academic_Level': 'Graduate', 'Country': 'Germany', 'Avg_Daily_Usage_Hours': 1.5, 'Most_Used_Platform': 'LinkedIn', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 8.0, 'Mental_Health_Score': 9, 'Relationship_Status': 'Single', 'Conflicts_Over_Social_Media': 0, 'Addicted_Score': 2}
{'Student_ID': 9, 'Age': 18, 'Gender': 'Male', 'Academic_Level': 'High School', 'Country': 'Japan', 'Avg_Daily_Usage_Hours': 4.0, 'Most_Used_Platform': 'TikTok', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 6.5, 'Mental_Health_Score': 7, 'Relationship_Status': 'Single', 'Conflicts_Over_Social_Media': 1, 'Addicted_Score': 5}
{'Student_ID': 11, 'Age': 19, 'Gender': 'Male', 'Academic_Level': 'Undergraduate', 'Country': 'France', 'Avg_Daily_Usage_Hours': 4.8, 'Most_Used_Platform': 'Snapchat', 'Affects_Academic_Performance': 'Yes', 'Sleep_Hours_Per_Night': 6.2, 'Mental_Health_Score': 5, 'Relationship_Status': 'Complicated', 'Conflicts_Over_Social_Media': 3, 'Addicted_Score': 7}
{'Student_ID': 13, 'Age': 22, 'Gender': 'Male', 'Academic_Level': 'Graduate', 'Country': 'Italy', 'Avg_Daily_Usage_Hours': 2.8, 'Most_Used_Platform': 'LinkedIn', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 7.2, 'Mental_Health_Score': 8, 'Relationship_Status': 'Single', 'Conflicts_Over_Social_Media': 1, 'Addicted_Score': 4}
{'Student_ID': 15, 'Age': 21, 'Gender': 'Male', 'Academic_Level': 'Undergraduate', 'Country': 'Russia', 'Avg_Daily_Usage_Hours': 3.7, 'Most_Used_Platform': 'YouTube', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 6.8, 'Mental_Health_Score': 7, 'Relationship_Status': 'In Relationship', 'Conflicts_Over_Social_Media': 2, 'Addicted_Score': 5}
{'Student_ID': 17, 'Age': 24, 'Gender': 'Male', 'Academic_Level': 'Graduate', 'Country': 'Sweden', 'Avg_Daily_Usage_Hours': 2.0, 'Most_Used_Platform': 'LinkedIn', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 7.8, 'Mental_Health_Score': 8, 'Relationship_Status': 'Single', 'Conflicts_Over_Social_Media': 0, 'Addicted_Score': 3}
{'Student_ID': 19, 'Age': 21, 'Gender': 'Male', 'Academic_Level': 'Undergraduate', 'Country': 'Denmark', 'Avg_Daily_Usage_Hours': 3.5, 'Most_Used_Platform': 'Facebook', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 6.7, 'Mental_Health_Score': 7, 'Relationship_Status': 'Single', 'Conflicts_Over_Social_Media': 1, 'Addicted_Score': 5}
{'Student_ID': 21, 'Age': 18, 'Gender': 'Male', 'Academic_Level': 'High School', 'Country': 'Belgium', 'Avg_Daily_Usage_Hours': 5.3, 'Most_Used_Platform': 'TikTok', 'Affects_Academic_Performance': 'Yes', 'Sleep_Hours_Per_Night': 5.5, 'Mental_Health_Score': 5, 'Relationship_Status': 'Single', 'Conflicts_Over_Social_Media': 4, 'Addicted_Score': 8}
{'Student_ID': 23, 'Age': 19, 'Gender': 'Male', 'Academic_Level': 'Undergraduate', 'Country': 'Austria', 'Avg_Daily_Usage_Hours': 4.9, 'Most_Used_Platform': 'Instagram', 'Affects_Academic_Performance': 'Yes', 'Sleep_Hours_Per_Night': 5.8, 'Mental_Health_Score': 6, 'Relationship_Status': 'Complicated', 'Conflicts_Over_Social_Media': 3, 'Addicted_Score': 7}
{'Student_ID': 25, 'Age': 22, 'Gender': 'Male', 'Academic_Level': 'Graduate', 'Country': 'Greece', 'Avg_Daily_Usage_Hours': 3.2, 'Most_Used_Platform': 'Facebook', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 6.9, 'Mental_Health_Score': 7, 'Relationship_Status': 'In Relationship', 'Conflicts_Over_Social_Media': 2, 'Addicted_Score': 5}
{'Student_ID': 27, 'Age': 21, 'Gender': 'Male', 'Academic_Level': 'Undergraduate', 'Country': 'New Zealand', 'Avg_Daily_Usage_Hours': 3.8, 'Most_Used_Platform': 'YouTube', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 6.6, 'Mental_Health_Score': 7, 'Relationship_Status': 'Single', 'Conflicts_Over_Social_Media': 1, 'Addicted_Score': 5}
{'Student_ID': 29, 'Age': 24, 'Gender': 'Male', 'Academic_Level': 'Graduate', 'Country': 'Malaysia', 'Avg_Daily_Usage_Hours': 2.2, 'Most_Used_Platform': 'LinkedIn', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 7.4, 'Mental_Health_Score': 8, 'Relationship_Status': 'Single', 'Conflicts_Over_Social_Media': 0, 'Addicted_Score': 3}
{'Student_ID': 31, 'Age': 21, 'Gender': 'Male', 'Academic_Level': 'Undergraduate', 'Country': 'Vietnam', 'Avg_Daily_Usage_Hours': 3.6, 'Most_Used_Platform': 'Facebook', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 6.7, 'Mental_Health_Score': 7, 'Relationship_Status': 'Single', 'Conflicts_Over_Social_Media': 1, 'Addicted_Score': 5}
{'Student_ID': 33, 'Age': 18, 'Gender': 'Male', 'Academic_Level': 'High School', 'Country': 'Indonesia', 'Avg_Daily_Usage_Hours': 5.4, 'Most_Used_Platform': 'TikTok', 'Affects_Academic_Performance': 'Yes', 'Sleep_Hours_Per_Night': 5.4, 'Mental_Health_Score': 5, 'Relationship_Status': 'Complicated', 'Conflicts_Over_Social_Media': 4, 'Addicted_Score': 8}
{'Student_ID': 35, 'Age': 19, 'Gender': 'Male', 'Academic_Level': 'Undergraduate', 'Country': 'Hong Kong', 'Avg_Daily_Usage_Hours': 4.7, 'Most_Used_Platform': 'Instagram', 'Affects_Academic_Performance': 'Yes', 'Sleep_Hours_Per_Night': 5.8, 'Mental_Health_Score': 6, 'Relationship_Status': 'In Relationship', 'Conflicts_Over_Social_Media': 3, 'Addicted_Score': 7}
{'Student_ID': 37, 'Age': 22, 'Gender': 'Male', 'Academic_Level': 'Graduate', 'Country': 'Israel', 'Avg_Daily_Usage_Hours': 3.1, 'Most_Used_Platform': 'Facebook', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 6.8, 'Mental_Health_Score': 7, 'Relationship_Status': 'Single', 'Conflicts_Over_Social_Media': 1, 'Addicted_Score': 5}
{'Student_ID': 39, 'Age': 21, 'Gender': 'Male', 'Academic_Level': 'Undergraduate', 'Country': 'Egypt', 'Avg_Daily_Usage_Hours': 3.9, 'Most_Used_Platform': 'YouTube', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 6.5, 'Mental_Health_Score': 7, 'Relationship_Status': 'Complicated', 'Conflicts_Over_Social_Media': 2, 'Addicted_Score': 6}
{'Student_ID': 41, 'Age': 24, 'Gender': 'Male', 'Academic_Level': 'Graduate', 'Country': 'South Africa', 'Avg_Daily_Usage_Hours': 2.3, 'Most_Used_Platform': 'LinkedIn', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 7.3, 'Mental_Health_Score': 8, 'Relationship_Status': 'In Relationship', 'Conflicts_Over_Social_Media': 1, 'Addicted_Score': 4}
{'Student_ID': 43, 'Age': 21, 'Gender': 'Male', 'Academic_Level': 'Undergraduate', 'Country': 'Kenya', 'Avg_Daily_Usage_Hours': 3.7, 'Most_Used_Platform': 'Facebook', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 6.6, 'Mental_Health_Score': 7, 'Relationship_Status': 'Single', 'Conflicts_Over_Social_Media': 2, 'Addicted_Score': 5}
{'Student_ID': 45, 'Age': 18, 'Gender': 'Male', 'Academic_Level': 'High School', 'Country': 'Argentina', 'Avg_Daily_Usage_Hours': 5.5, 'Most_Used_Platform': 'TikTok', 'Affects_Academic_Performance': 'Yes', 'Sleep_Hours_Per_Night': 5.3, 'Mental_Health_Score': 5, 'Relationship_Status': 'Single', 'Conflicts_Over_Social_Media': 4, 'Addicted_Score': 8}
{'Student_ID': 47, 'Age': 19, 'Gender': 'Male', 'Academic_Level': 'Undergraduate', 'Country': 'Colombia', 'Avg_Daily_Usage_Hours': 4.8, 'Most_Used_Platform': 'Instagram', 'Affects_Academic_Performance': 'Yes', 'Sleep_Hours_Per_Night': 5.9, 'Mental_Health_Score': 6, 'Relationship_Status': 'In Relationship', 'Conflicts_Over_Social_Media': 3, 'Addicted_Score': 7}
{'Student_ID': 49, 'Age': 22, 'Gender': 'Male', 'Academic_Level': 'Graduate', 'Country': 'Venezuela', 'Avg_Daily_Usage_Hours': 3.3, 'Most_Used_Platform': 'Facebook', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 6.7, 'Mental_Health_Score': 7, 'Relationship_Status': 'In Relationship', 'Conflicts_Over_Social_Media': 2, 'Addicted_Score': 5}
{'Student_ID': 51, 'Age': 21, 'Gender': 'Male', 'Academic_Level': 'Undergraduate', 'Country': 'Uruguay', 'Avg_Daily_Usage_Hours': 3.8, 'Most_Used_Platform': 'YouTube', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 6.4, 'Mental_Health_Score': 7, 'Relationship_Status': 'Single', 'Conflicts_Over_Social_Media': 2, 'Addicted_Score': 6}
{'Student_ID': 53, 'Age': 24, 'Gender': 'Male', 'Academic_Level': 'Graduate', 'Country': 'Bolivia', 'Avg_Daily_Usage_Hours': 2.4, 'Most_Used_Platform': 'LinkedIn', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 7.2, 'Mental_Health_Score': 8, 'Relationship_Status': 'Complicated', 'Conflicts_Over_Social_Media': 1, 'Addicted_Score': 4}
{'Student_ID': 55, 'Age': 21, 'Gender': 'Male', 'Academic_Level': 'Undergraduate', 'Country': 'Panama', 'Avg_Daily_Usage_Hours': 3.6, 'Most_Used_Platform': 'Facebook', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 6.5, 'Mental_Health_Score': 7, 'Relationship_Status': 'In Relationship', 'Conflicts_Over_Social_Media': 2, 'Addicted_Score': 5}
{'Student_ID': 57, 'Age': 18, 'Gender': 'Male', 'Academic_Level': 'High School', 'Country': 'Trinidad', 'Avg_Daily_Usage_Hours': 5.6, 'Most_Used_Platform': 'TikTok', 'Affects_Academic_Performance': 'Yes', 'Sleep_Hours_Per_Night': 5.2, 'Mental_Health_Score': 5, 'Relationship_Status': 'Single', 'Conflicts_Over_Social_Media': 4, 'Addicted_Score': 8}
{'Student_ID': 59, 'Age': 19, 'Gender': 'Male', 'Academic_Level': 'Undergraduate', 'Country': 'Iceland', 'Avg_Daily_Usage_Hours': 4.6, 'Most_Used_Platform': 'Instagram', 'Affects_Academic_Performance': 'Yes', 'Sleep_Hours_Per_Night': 5.9, 'Mental_Health_Score': 6, 'Relationship_Status': 'Complicated', 'Conflicts_Over_Social_Media': 3, 'Addicted_Score': 7}
{'Student_ID': 61, 'Age': 22, 'Gender': 'Male', 'Academic_Level': 'Graduate', 'Country': 'Poland', 'Avg_Daily_Usage_Hours': 3.1, 'Most_Used_Platform': 'Facebook', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 7.1, 'Mental_Health_Score': 7, 'Relationship_Status': 'Single', 'Conflicts_Over_Social_Media': 1, 'Addicted_Score': 5}
{'Student_ID': 63, 'Age': 20, 'Gender': 'Male', 'Academic_Level': 'Undergraduate', 'Country': 'Hungary', 'Avg_Daily_Usage_Hours': 4.2, 'Most_Used_Platform': 'TikTok', 'Affects_Academic_Performance': 'Yes', 'Sleep_Hours_Per_Night': 6.0, 'Mental_Health_Score': 6, 'Relationship_Status': 'Complicated', 'Conflicts_Over_Social_Media': 3, 'Addicted_Score': 7}
{'Student_ID': 65, 'Age': 23, 'Gender': 'Male', 'Academic_Level': 'Graduate', 'Country': 'Slovakia', 'Avg_Daily_Usage_Hours': 2.3, 'Most_Used_Platform': 'LinkedIn', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 7.4, 'Mental_Health_Score': 8, 'Relationship_Status': 'In Relationship', 'Conflicts_Over_Social_Media': 1, 'Addicted_Score': 3}
{'Student_ID': 67, 'Age': 20, 'Gender': 'Male', 'Academic_Level': 'Undergraduate', 'Country': 'Serbia', 'Avg_Daily_Usage_Hours': 3.9, 'Most_Used_Platform': 'YouTube', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 6.5, 'Mental_Health_Score': 7, 'Relationship_Status': 'Complicated', 'Conflicts_Over_Social_Media': 2, 'Addicted_Score': 6}
{'Student_ID': 69, 'Age': 22, 'Gender': 'Male', 'Academic_Level': 'Graduate', 'Country': 'Bulgaria', 'Avg_Daily_Usage_Hours': 2.8, 'Most_Used_Platform': 'LinkedIn', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 7.2, 'Mental_Health_Score': 8, 'Relationship_Status': 'Single', 'Conflicts_Over_Social_Media': 1, 'Addicted_Score': 4}
{'Student_ID': 71, 'Age': 18, 'Gender': 'Male', 'Academic_Level': 'High School', 'Country': 'Latvia', 'Avg_Daily_Usage_Hours': 5.4, 'Most_Used_Platform': 'Snapchat', 'Affects_Academic_Performance': 'Yes', 'Sleep_Hours_Per_Night': 5.5, 'Mental_Health_Score': 5, 'Relationship_Status': 'Single', 'Conflicts_Over_Social_Media': 4, 'Addicted_Score': 8}
{'Student_ID': 73, 'Age': 19, 'Gender': 'Male', 'Academic_Level': 'Undergraduate', 'Country': 'Ukraine', 'Avg_Daily_Usage_Hours': 4.9, 'Most_Used_Platform': 'TikTok', 'Affects_Academic_Performance': 'Yes', 'Sleep_Hours_Per_Night': 5.7, 'Mental_Health_Score': 6, 'Relationship_Status': 'Complicated', 'Conflicts_Over_Social_Media': 3, 'Addicted_Score': 7}
{'Student_ID': 75, 'Age': 23, 'Gender': 'Male', 'Academic_Level': 'Graduate', 'Country': 'Belarus', 'Avg_Daily_Usage_Hours': 2.5, 'Most_Used_Platform': 'LinkedIn', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 7.3, 'Mental_Health_Score': 8, 'Relationship_Status': 'In Relationship', 'Conflicts_Over_Social_Media': 1, 'Addicted_Score': 4}
{'Student_ID': 77, 'Age': 19, 'Gender': 'Male', 'Academic_Level': 'High School', 'Country': 'Uzbekistan', 'Avg_Daily_Usage_Hours': 5.5, 'Most_Used_Platform': 'TikTok', 'Affects_Academic_Performance': 'Yes', 'Sleep_Hours_Per_Night': 5.4, 'Mental_Health_Score': 5, 'Relationship_Status': 'Complicated', 'Conflicts_Over_Social_Media': 4, 'Addicted_Score': 8}
{'Student_ID': 79, 'Age': 20, 'Gender': 'Male', 'Academic_Level': 'Undergraduate', 'Country': 'Tajikistan', 'Avg_Daily_Usage_Hours': 4.7, 'Most_Used_Platform': 'YouTube', 'Affects_Academic_Performance': 'Yes', 'Sleep_Hours_Per_Night': 5.9, 'Mental_Health_Score': 6, 'Relationship_Status': 'Single', 'Conflicts_Over_Social_Media': 3, 'Addicted_Score': 7}
{'Student_ID': 81, 'Age': 21, 'Gender': 'Male', 'Academic_Level': 'Graduate', 'Country': 'Georgia', 'Avg_Daily_Usage_Hours': 3.0, 'Most_Used_Platform': 'LinkedIn', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 7.1, 'Mental_Health_Score': 8, 'Relationship_Status': 'In Relationship', 'Conflicts_Over_Social_Media': 1, 'Addicted_Score': 4}
{'Student_ID': 83, 'Age': 20, 'Gender': 'Male', 'Academic_Level': 'Undergraduate', 'Country': 'Cyprus', 'Avg_Daily_Usage_Hours': 3.8, 'Most_Used_Platform': 'Facebook', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 6.6, 'Mental_Health_Score': 7, 'Relationship_Status': 'Complicated', 'Conflicts_Over_Social_Media': 2, 'Addicted_Score': 6}
{'Student_ID': 85, 'Age': 18, 'Gender': 'Male', 'Academic_Level': 'High School', 'Country': 'Luxembourg', 'Avg_Daily_Usage_Hours': 5.6, 'Most_Used_Platform': 'Snapchat', 'Affects_Academic_Performance': 'Yes', 'Sleep_Hours_Per_Night': 5.3, 'Mental_Health_Score': 5, 'Relationship_Status': 'Single', 'Conflicts_Over_Social_Media': 4, 'Addicted_Score': 8}
{'Student_ID': 87, 'Age': 19, 'Gender': 'Male', 'Academic_Level': 'High School', 'Country': 'Andorra', 'Avg_Daily_Usage_Hours': 5.3, 'Most_Used_Platform': 'TikTok', 'Affects_Academic_Performance': 'Yes', 'Sleep_Hours_Per_Night': 5.5, 'Mental_Health_Score': 5, 'Relationship_Status': 'In Relationship', 'Conflicts_Over_Social_Media': 4, 'Addicted_Score': 8}
{'Student_ID': 89, 'Age': 20, 'Gender': 'Male', 'Academic_Level': 'Undergraduate', 'Country': 'Vatican City', 'Avg_Daily_Usage_Hours': 4.4, 'Most_Used_Platform': 'YouTube', 'Affects_Academic_Performance': 'Yes', 'Sleep_Hours_Per_Night': 6.0, 'Mental_Health_Score': 6, 'Relationship_Status': 'Complicated', 'Conflicts_Over_Social_Media': 3, 'Addicted_Score': 7}
{'Student_ID': 91, 'Age': 22, 'Gender': 'Male', 'Academic_Level': 'Graduate', 'Country': 'Montenegro', 'Avg_Daily_Usage_Hours': 2.9, 'Most_Used_Platform': 'Facebook', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 7.0, 'Mental_Health_Score': 7, 'Relationship_Status': 'In Relationship', 'Conflicts_Over_Social_Media': 2, 'Addicted_Score': 5}
{'Student_ID': 93, 'Age': 21, 'Gender': 'Male', 'Academic_Level': 'Undergraduate', 'Country': 'North Macedonia', 'Avg_Daily_Usage_Hours': 3.7, 'Most_Used_Platform': 'Snapchat', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 6.5, 'Mental_Health_Score': 7, 'Relationship_Status': 'Single', 'Conflicts_Over_Social_Media': 2, 'Addicted_Score': 6}
{'Student_ID': 95, 'Age': 23, 'Gender': 'Male', 'Academic_Level': 'Graduate', 'Country': 'Bosnia', 'Avg_Daily_Usage_Hours': 2.4, 'Most_Used_Platform': 'LinkedIn', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 7.4, 'Mental_Health_Score': 8, 'Relationship_Status': 'Complicated', 'Conflicts_Over_Social_Media': 1, 'Addicted_Score': 4}
{'Student_ID': 97, 'Age': 18, 'Gender': 'Male', 'Academic_Level': 'High School', 'Country': 'Kuwait', 'Avg_Daily_Usage_Hours': 5.7, 'Most_Used_Platform': 'Snapchat', 'Affects_Academic_Performance': 'Yes', 'Sleep_Hours_Per_Night': 5.3, 'Mental_Health_Score': 5, 'Relationship_Status': 'In Relationship', 'Conflicts_Over_Social_Media': 4, 'Addicted_Score': 8}
{'Student_ID': 99, 'Age': 20, 'Gender': 'Male', 'Academic_Level': 'Undergraduate', 'Country': 'Oman', 'Avg_Daily_Usage_Hours': 4.6, 'Most_Used_Platform': 'Instagram', 'Affects_Academic_Performance': 'Yes', 'Sleep_Hours_Per_Night': 5.9, 'Mental_Health_Score': 6, 'Relationship_Status': 'Single', 'Conflicts_Over_Social_Media': 3, 'Addicted_Score': 7}
{'Student_ID': 101, 'Age': 19, 'Gender': 'Male', 'Academic_Level': 'High School', 'Country': 'Lebanon', 'Avg_Daily_Usage_Hours': 5.8, 'Most_Used_Platform': 'YouTube', 'Affects_Academic_Performance': 'Yes', 'Sleep_Hours_Per_Night': 5.2, 'Mental_Health_Score': 5, 'Relationship_Status': 'Complicated', 'Conflicts_Over_Social_Media': 4, 'Addicted_Score': 9}
{'Student_ID': 103, 'Age': 20, 'Gender': 'Male', 'Academic_Level': 'Undergraduate', 'Country': 'Yemen', 'Avg_Daily_Usage_Hours': 4.7, 'Most_Used_Platform': 'Facebook', 'Affects_Academic_Performance': 'Yes', 'Sleep_Hours_Per_Night': 5.8, 'Mental_Health_Score': 6, 'Relationship_Status': 'In Relationship', 'Conflicts_Over_Social_Media': 3, 'Addicted_Score': 7}
{'Student_ID': 105, 'Age': 22, 'Gender': 'Male', 'Academic_Level': 'Graduate', 'Country': 'Afghanistan', 'Avg_Daily_Usage_Hours': 2.9, 'Most_Used_Platform': 'LinkedIn', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 7.0, 'Mental_Health_Score': 7, 'Relationship_Status': 'Complicated', 'Conflicts_Over_Social_Media': 2, 'Addicted_Score': 5}
{'Student_ID': 107, 'Age': 21, 'Gender': 'Male', 'Academic_Level': 'Undergraduate', 'Country': 'Nepal', 'Avg_Daily_Usage_Hours': 3.8, 'Most_Used_Platform': 'YouTube', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 6.6, 'Mental_Health_Score': 7, 'Relationship_Status': 'Single', 'Conflicts_Over_Social_Media': 2, 'Addicted_Score': 6}
{'Student_ID': 109, 'Age': 23, 'Gender': 'Male', 'Academic_Level': 'Graduate', 'Country': 'Sri Lanka', 'Avg_Daily_Usage_Hours': 2.6, 'Most_Used_Platform': 'LinkedIn', 'Affects_Academic_Performance': 'No', 'Sleep_Hours_Per_Night': 7.2, 'Mental_Health_Score': 8, 'Relationship_Status': 'In Relationship', 'Conflicts_Over_Social_Media': 1, 'Addicted_Score': 4}
{'Student_ID': 111, 'Age': 20, 'Gender': 'Male', 'Academic_Level': 'Undergraduate', 'Country': 'Bangladesh', 'Avg_Daily_Usage_Hours': 6.1, 'Most_Used_Platform': 'Instagram', 'Affects_Academic_Performance': 'Yes', 'Sleep_Hours_Per_Night': 6.2, 'Mental_Health_Score': 5, 'Relationship_Status': 'Single', 'Conflicts_Over_Social_Media': 4, 'Addicted_Score': 8}

In [11]:
def average_usage():
    total = 0
    count = 0

    for student in students:
        total += student.get("Daily_Usage_Hours", 0)
        count += 1

    if count > 0:
        print("Average Daily Usage Hours:", round(total / count, 2))
    else:
        print("No data available.")

In [12]:
average_usage()

Average Daily Usage Hours: 0.0

In [13]:
def save_to_file():
    new_df = pd.DataFrame(students)
    new_df.to_csv("Student_Addiction_Output.csv", index=False)
    print("Data saved successfully to Student_Addiction_Output.csv")

In [14]:
save_to_file()

Data saved successfully to Student_Addiction_Output.csv

In [15]:
while True:
    print("\n--- STUDENT SOCIAL MEDIA ADDICTION SYSTEM ---")
    print("1. View all students")
    print("2. Search students by gender")
    print("3. Show average daily usage")
    print("4. Save records to file")
    print("5. Exit")

    try:
        choice = int(input("Enter your choice: "))

        if choice == 1:
            view_students()

        elif choice == 2:
            search_by_gender()

        elif choice == 3:
            average_usage()

        elif choice == 4:
            save_to_file()

        elif choice == 5:
            print("Program exited.")
            break

        else:
            print("Invalid choice. Enter 1 to 5.")

    except ValueError:
        print("Please enter a valid number.")

--- STUDENT SOCIAL MEDIA ADDICTION SYSTEM ---
1. View all students
2. Search students by gender
3. Show average daily usage
4. Save records to file
5. Exit

Enter your choice:  1

Student 1
Student_ID : 1
Age : 19
Gender : Female
Academic_Level : Undergraduate
Country : Bangladesh
Avg_Daily_Usage_Hours : 5.2
Most_Used_Platform : Instagram
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 6.5
Mental_Health_Score : 6
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 3
Addicted_Score : 8

Student 2
Student_ID : 2
Age : 22
Gender : Male
Academic_Level : Graduate
Country : India
Avg_Daily_Usage_Hours : 2.1
Most_Used_Platform : Twitter
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 7.5
Mental_Health_Score : 8
Relationship_Status : Single
Conflicts_Over_Social_Media : 0
Addicted_Score : 3

Student 3
Student_ID : 3
Age : 20
Gender : Female
Academic_Level : Undergraduate
Country : USA
Avg_Daily_Usage_Hours : 6.0
Most_Used_Platform : TikTok
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.0
Mental_Health_Score : 5
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 4
Addicted_Score : 9

Student 4
Student_ID : 4
Age : 18
Gender : Male
Academic_Level : High School
Country : UK
Avg_Daily_Usage_Hours : 3.0
Most_Used_Platform : YouTube
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 7.0
Mental_Health_Score : 7
Relationship_Status : Single
Conflicts_Over_Social_Media : 1
Addicted_Score : 4

Student 5
Student_ID : 5
Age : 21
Gender : Male
Academic_Level : Graduate
Country : Canada
Avg_Daily_Usage_Hours : 4.5
Most_Used_Platform : Facebook
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 6.0
Mental_Health_Score : 6
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 2
Addicted_Score : 7

Student 6
Student_ID : 6
Age : 19
Gender : Female
Academic_Level : Undergraduate
Country : Australia
Avg_Daily_Usage_Hours : 7.2
Most_Used_Platform : Instagram
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 4.5
Mental_Health_Score : 4
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 5
Addicted_Score : 9

Student 7
Student_ID : 7
Age : 23
Gender : Male
Academic_Level : Graduate
Country : Germany
Avg_Daily_Usage_Hours : 1.5
Most_Used_Platform : LinkedIn
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 8.0
Mental_Health_Score : 9
Relationship_Status : Single
Conflicts_Over_Social_Media : 0
Addicted_Score : 2

Student 8
Student_ID : 8
Age : 20
Gender : Female
Academic_Level : Undergraduate
Country : Brazil
Avg_Daily_Usage_Hours : 5.8
Most_Used_Platform : Snapchat
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 6.0
Mental_Health_Score : 6
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 2
Addicted_Score : 8

Student 9
Student_ID : 9
Age : 18
Gender : Male
Academic_Level : High School
Country : Japan
Avg_Daily_Usage_Hours : 4.0
Most_Used_Platform : TikTok
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 6.5
Mental_Health_Score : 7
Relationship_Status : Single
Conflicts_Over_Social_Media : 1
Addicted_Score : 5

Student 10
Student_ID : 10
Age : 21
Gender : Female
Academic_Level : Graduate
Country : South Korea
Avg_Daily_Usage_Hours : 3.3
Most_Used_Platform : Instagram
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 7.0
Mental_Health_Score : 7
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 1
Addicted_Score : 4

Student 11
Student_ID : 11
Age : 19
Gender : Male
Academic_Level : Undergraduate
Country : France
Avg_Daily_Usage_Hours : 4.8
Most_Used_Platform : Snapchat
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 6.2
Mental_Health_Score : 5
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 3
Addicted_Score : 7

Student 12
Student_ID : 12
Age : 20
Gender : Female
Academic_Level : Undergraduate
Country : Spain
Avg_Daily_Usage_Hours : 5.5
Most_Used_Platform : TikTok
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.8
Mental_Health_Score : 6
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 2
Addicted_Score : 8

Student 13
Student_ID : 13
Age : 22
Gender : Male
Academic_Level : Graduate
Country : Italy
Avg_Daily_Usage_Hours : 2.8
Most_Used_Platform : LinkedIn
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 7.2
Mental_Health_Score : 8
Relationship_Status : Single
Conflicts_Over_Social_Media : 1
Addicted_Score : 4

Student 14
Student_ID : 14
Age : 18
Gender : Female
Academic_Level : High School
Country : Mexico
Avg_Daily_Usage_Hours : 6.5
Most_Used_Platform : Instagram
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.5
Mental_Health_Score : 5
Relationship_Status : Single
Conflicts_Over_Social_Media : 4
Addicted_Score : 9

Student 15
Student_ID : 15
Age : 21
Gender : Male
Academic_Level : Undergraduate
Country : Russia
Avg_Daily_Usage_Hours : 3.7
Most_Used_Platform : YouTube
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 6.8
Mental_Health_Score : 7
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 2
Addicted_Score : 5

Student 16
Student_ID : 16
Age : 20
Gender : Female
Academic_Level : Undergraduate
Country : China
Avg_Daily_Usage_Hours : 4.2
Most_Used_Platform : TikTok
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 6.0
Mental_Health_Score : 6
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 3
Addicted_Score : 7

Student 17
Student_ID : 17
Age : 24
Gender : Male
Academic_Level : Graduate
Country : Sweden
Avg_Daily_Usage_Hours : 2.0
Most_Used_Platform : LinkedIn
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 7.8
Mental_Health_Score : 8
Relationship_Status : Single
Conflicts_Over_Social_Media : 0
Addicted_Score : 3

Student 18
Student_ID : 18
Age : 19
Gender : Female
Academic_Level : High School
Country : Norway
Avg_Daily_Usage_Hours : 5.0
Most_Used_Platform : Instagram
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.7
Mental_Health_Score : 5
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 3
Addicted_Score : 8

Student 19
Student_ID : 19
Age : 21
Gender : Male
Academic_Level : Undergraduate
Country : Denmark
Avg_Daily_Usage_Hours : 3.5
Most_Used_Platform : Facebook
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 6.7
Mental_Health_Score : 7
Relationship_Status : Single
Conflicts_Over_Social_Media : 1
Addicted_Score : 5

Student 20
Student_ID : 20
Age : 20
Gender : Female
Academic_Level : Undergraduate
Country : Netherlands
Avg_Daily_Usage_Hours : 4.7
Most_Used_Platform : Snapchat
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.9
Mental_Health_Score : 6
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 3
Addicted_Score : 7

Student 21
Student_ID : 21
Age : 18
Gender : Male
Academic_Level : High School
Country : Belgium
Avg_Daily_Usage_Hours : 5.3
Most_Used_Platform : TikTok
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.5
Mental_Health_Score : 5
Relationship_Status : Single
Conflicts_Over_Social_Media : 4
Addicted_Score : 8

Student 22
Student_ID : 22
Age : 23
Gender : Female
Academic_Level : Graduate
Country : Switzerland
Avg_Daily_Usage_Hours : 2.5
Most_Used_Platform : LinkedIn
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 7.3
Mental_Health_Score : 8
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 1
Addicted_Score : 4

Student 23
Student_ID : 23
Age : 19
Gender : Male
Academic_Level : Undergraduate
Country : Austria
Avg_Daily_Usage_Hours : 4.9
Most_Used_Platform : Instagram
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.8
Mental_Health_Score : 6
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 3
Addicted_Score : 7

Student 24
Student_ID : 24
Age : 20
Gender : Female
Academic_Level : Undergraduate
Country : Portugal
Avg_Daily_Usage_Hours : 5.7
Most_Used_Platform : TikTok
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.4
Mental_Health_Score : 5
Relationship_Status : Single
Conflicts_Over_Social_Media : 4
Addicted_Score : 8

Student 25
Student_ID : 25
Age : 22
Gender : Male
Academic_Level : Graduate
Country : Greece
Avg_Daily_Usage_Hours : 3.2
Most_Used_Platform : Facebook
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 6.9
Mental_Health_Score : 7
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 2
Addicted_Score : 5

Student 26
Student_ID : 26
Age : 19
Gender : Female
Academic_Level : High School
Country : Ireland
Avg_Daily_Usage_Hours : 6.1
Most_Used_Platform : Instagram
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.2
Mental_Health_Score : 5
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 4
Addicted_Score : 9

Student 27
Student_ID : 27
Age : 21
Gender : Male
Academic_Level : Undergraduate
Country : New Zealand
Avg_Daily_Usage_Hours : 3.8
Most_Used_Platform : YouTube
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 6.6
Mental_Health_Score : 7
Relationship_Status : Single
Conflicts_Over_Social_Media : 1
Addicted_Score : 5

Student 28
Student_ID : 28
Age : 20
Gender : Female
Academic_Level : Undergraduate
Country : Singapore
Avg_Daily_Usage_Hours : 4.4
Most_Used_Platform : TikTok
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.9
Mental_Health_Score : 6
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 3
Addicted_Score : 7

Student 29
Student_ID : 29
Age : 24
Gender : Male
Academic_Level : Graduate
Country : Malaysia
Avg_Daily_Usage_Hours : 2.2
Most_Used_Platform : LinkedIn
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 7.4
Mental_Health_Score : 8
Relationship_Status : Single
Conflicts_Over_Social_Media : 0
Addicted_Score : 3

Student 30
Student_ID : 30
Age : 19
Gender : Female
Academic_Level : High School
Country : Thailand
Avg_Daily_Usage_Hours : 5.9
Most_Used_Platform : Instagram
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.3
Mental_Health_Score : 5
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 4
Addicted_Score : 8

Student 31
Student_ID : 31
Age : 21
Gender : Male
Academic_Level : Undergraduate
Country : Vietnam
Avg_Daily_Usage_Hours : 3.6
Most_Used_Platform : Facebook
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 6.7
Mental_Health_Score : 7
Relationship_Status : Single
Conflicts_Over_Social_Media : 1
Addicted_Score : 5

Student 32
Student_ID : 32
Age : 20
Gender : Female
Academic_Level : Undergraduate
Country : Philippines
Avg_Daily_Usage_Hours : 4.8
Most_Used_Platform : Snapchat
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.7
Mental_Health_Score : 6
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 3
Addicted_Score : 7

Student 33
Student_ID : 33
Age : 18
Gender : Male
Academic_Level : High School
Country : Indonesia
Avg_Daily_Usage_Hours : 5.4
Most_Used_Platform : TikTok
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.4
Mental_Health_Score : 5
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 4
Addicted_Score : 8

Student 34
Student_ID : 34
Age : 23
Gender : Female
Academic_Level : Graduate
Country : Taiwan
Avg_Daily_Usage_Hours : 2.6
Most_Used_Platform : LinkedIn
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 7.2
Mental_Health_Score : 8
Relationship_Status : Single
Conflicts_Over_Social_Media : 1
Addicted_Score : 4

Student 35
Student_ID : 35
Age : 19
Gender : Male
Academic_Level : Undergraduate
Country : Hong Kong
Avg_Daily_Usage_Hours : 4.7
Most_Used_Platform : Instagram
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.8
Mental_Health_Score : 6
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 3
Addicted_Score : 7

Student 36
Student_ID : 36
Age : 20
Gender : Female
Academic_Level : Undergraduate
Country : Turkey
Avg_Daily_Usage_Hours : 5.6
Most_Used_Platform : TikTok
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.5
Mental_Health_Score : 5
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 4
Addicted_Score : 8

Student 37
Student_ID : 37
Age : 22
Gender : Male
Academic_Level : Graduate
Country : Israel
Avg_Daily_Usage_Hours : 3.1
Most_Used_Platform : Facebook
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 6.8
Mental_Health_Score : 7
Relationship_Status : Single
Conflicts_Over_Social_Media : 1
Addicted_Score : 5

Student 38
Student_ID : 38
Age : 19
Gender : Female
Academic_Level : High School
Country : UAE
Avg_Daily_Usage_Hours : 6.2
Most_Used_Platform : Instagram
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.1
Mental_Health_Score : 5
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 4
Addicted_Score : 9

Student 39
Student_ID : 39
Age : 21
Gender : Male
Academic_Level : Undergraduate
Country : Egypt
Avg_Daily_Usage_Hours : 3.9
Most_Used_Platform : YouTube
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 6.5
Mental_Health_Score : 7
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 2
Addicted_Score : 6

Student 40
Student_ID : 40
Age : 20
Gender : Female
Academic_Level : Undergraduate
Country : Morocco
Avg_Daily_Usage_Hours : 4.5
Most_Used_Platform : TikTok
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.8
Mental_Health_Score : 6
Relationship_Status : Single
Conflicts_Over_Social_Media : 3
Addicted_Score : 7

Student 41
Student_ID : 41
Age : 24
Gender : Male
Academic_Level : Graduate
Country : South Africa
Avg_Daily_Usage_Hours : 2.3
Most_Used_Platform : LinkedIn
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 7.3
Mental_Health_Score : 8
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 1
Addicted_Score : 4

Student 42
Student_ID : 42
Age : 19
Gender : Female
Academic_Level : High School
Country : Nigeria
Avg_Daily_Usage_Hours : 5.8
Most_Used_Platform : Instagram
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.4
Mental_Health_Score : 5
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 4
Addicted_Score : 8

Student 43
Student_ID : 43
Age : 21
Gender : Male
Academic_Level : Undergraduate
Country : Kenya
Avg_Daily_Usage_Hours : 3.7
Most_Used_Platform : Facebook
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 6.6
Mental_Health_Score : 7
Relationship_Status : Single
Conflicts_Over_Social_Media : 2
Addicted_Score : 5

Student 44
Student_ID : 44
Age : 20
Gender : Female
Academic_Level : Undergraduate
Country : Ghana
Avg_Daily_Usage_Hours : 4.6
Most_Used_Platform : Snapchat
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.7
Mental_Health_Score : 6
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 3
Addicted_Score : 7

Student 45
Student_ID : 45
Age : 18
Gender : Male
Academic_Level : High School
Country : Argentina
Avg_Daily_Usage_Hours : 5.5
Most_Used_Platform : TikTok
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.3
Mental_Health_Score : 5
Relationship_Status : Single
Conflicts_Over_Social_Media : 4
Addicted_Score : 8

Student 46
Student_ID : 46
Age : 23
Gender : Female
Academic_Level : Graduate
Country : Chile
Avg_Daily_Usage_Hours : 2.7
Most_Used_Platform : LinkedIn
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 7.1
Mental_Health_Score : 8
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 1
Addicted_Score : 4

Student 47
Student_ID : 47
Age : 19
Gender : Male
Academic_Level : Undergraduate
Country : Colombia
Avg_Daily_Usage_Hours : 4.8
Most_Used_Platform : Instagram
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.9
Mental_Health_Score : 6
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 3
Addicted_Score : 7

Student 48
Student_ID : 48
Age : 20
Gender : Female
Academic_Level : Undergraduate
Country : Peru
Avg_Daily_Usage_Hours : 5.5
Most_Used_Platform : TikTok
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.6
Mental_Health_Score : 5
Relationship_Status : Single
Conflicts_Over_Social_Media : 4
Addicted_Score : 8

Student 49
Student_ID : 49
Age : 22
Gender : Male
Academic_Level : Graduate
Country : Venezuela
Avg_Daily_Usage_Hours : 3.3
Most_Used_Platform : Facebook
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 6.7
Mental_Health_Score : 7
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 2
Addicted_Score : 5

Student 50
Student_ID : 50
Age : 19
Gender : Female
Academic_Level : High School
Country : Ecuador
Avg_Daily_Usage_Hours : 6.3
Most_Used_Platform : Instagram
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.2
Mental_Health_Score : 5
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 4
Addicted_Score : 9

Student 51
Student_ID : 51
Age : 21
Gender : Male
Academic_Level : Undergraduate
Country : Uruguay
Avg_Daily_Usage_Hours : 3.8
Most_Used_Platform : YouTube
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 6.4
Mental_Health_Score : 7
Relationship_Status : Single
Conflicts_Over_Social_Media : 2
Addicted_Score : 6

Student 52
Student_ID : 52
Age : 20
Gender : Female
Academic_Level : Undergraduate
Country : Paraguay
Avg_Daily_Usage_Hours : 4.7
Most_Used_Platform : TikTok
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.8
Mental_Health_Score : 6
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 3
Addicted_Score : 7

Student 53
Student_ID : 53
Age : 24
Gender : Male
Academic_Level : Graduate
Country : Bolivia
Avg_Daily_Usage_Hours : 2.4
Most_Used_Platform : LinkedIn
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 7.2
Mental_Health_Score : 8
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 1
Addicted_Score : 4

Student 54
Student_ID : 54
Age : 19
Gender : Female
Academic_Level : High School
Country : Costa Rica
Avg_Daily_Usage_Hours : 5.7
Most_Used_Platform : Instagram
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.5
Mental_Health_Score : 5
Relationship_Status : Single
Conflicts_Over_Social_Media : 4
Addicted_Score : 8

Student 55
Student_ID : 55
Age : 21
Gender : Male
Academic_Level : Undergraduate
Country : Panama
Avg_Daily_Usage_Hours : 3.6
Most_Used_Platform : Facebook
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 6.5
Mental_Health_Score : 7
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 2
Addicted_Score : 5

Student 56
Student_ID : 56
Age : 20
Gender : Female
Academic_Level : Undergraduate
Country : Jamaica
Avg_Daily_Usage_Hours : 4.9
Most_Used_Platform : Snapchat
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.6
Mental_Health_Score : 6
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 3
Addicted_Score : 7

Student 57
Student_ID : 57
Age : 18
Gender : Male
Academic_Level : High School
Country : Trinidad
Avg_Daily_Usage_Hours : 5.6
Most_Used_Platform : TikTok
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.2
Mental_Health_Score : 5
Relationship_Status : Single
Conflicts_Over_Social_Media : 4
Addicted_Score : 8

Student 58
Student_ID : 58
Age : 23
Gender : Female
Academic_Level : Graduate
Country : Bahamas
Avg_Daily_Usage_Hours : 2.8
Most_Used_Platform : LinkedIn
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 7.0
Mental_Health_Score : 8
Relationship_Status : In Relationship
Conflicts_Over_Social_Media : 1
Addicted_Score : 4

Student 59
Student_ID : 59
Age : 19
Gender : Male
Academic_Level : Undergraduate
Country : Iceland
Avg_Daily_Usage_Hours : 4.6
Most_Used_Platform : Instagram
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.9
Mental_Health_Score : 6
Relationship_Status : Complicated
Conflicts_Over_Social_Media : 3
Addicted_Score : 7

Student 60
Student_ID : 60
Age : 20
Gender : Female
Academic_Level : Undergraduate
Country : Finland
Avg_Daily_Usage_Hours : 5.4
Most_Used_Platform : TikTok
Affects_Academic_Performance : Yes
Sleep_Hours_Per_Night : 5.7
Mental_Health_Score : 5
Relationship_Status : Single
Conflicts_Over_Social_Media : 4
Addicted_Score : 8

Student 61
Student_ID : 61
Age : 22
Gender : Male
Academic_Level : Graduate
Country : Poland
Avg_Daily_Usage_Hours : 3.1
Most_Used_Platform : Facebook
Affects_Academic_Performance : No
Sleep_Hours_Per_Night : 7.1
Mental_Health_Score : 7
Relationship_Status : Single
Conflicts_Over_Social_Media : 1
Addicted_Score : 5

Student 62

Enter your choice:  2
Enter gender to search:  3

No matching records found.

--- STUDENT SOCIAL MEDIA ADDICTION SYSTEM ---
1. View all students
2. Search students by gender
3. Show average daily usage
4. Save records to file
5. Exit

Enter your choice:  4

Data saved successfully to Student_Addiction_Output.csv

--- STUDENT SOCIAL MEDIA ADDICTION SYSTEM ---
1. View all students
2. Search students by gender
3. Show average daily usage
4. Save records to file
5. Exit

Enter your choice:  5

Program exited.