In [1]:
import pandas as pd
import numpy as np

In [2]:
# Step 1
# Load the data
df= pd.read_csv(r"C:\Users\user\Downloads\budgetwise_finance_dataset.csv")
df

,transaction_id,user_id,date,transaction_type,category,amount,payment_mode,location,notes
0,T4999,U018,2023-04-25,Expense,Educaton,3888,card,Ahmedabad,Movie tickets
1,T12828,U133,08/05/2022,Expense,rent,649,NaN,Hyderabad,asdfgh
2,T7403,U091,31-12-23,Income,Freelance,13239,Csh,BAN,Books
3,T12350,U097,NaN,Expense,Fod,6299,Bank Transfer,AHMEDABAD,Electricity bill
4,T7495,U088,10/28/2022,Expense,entertainment,2287,CARD,Hyderabad,NaN
...,...,...,...,...,...,...,...,...,...
15895,T7467,U033,21-07-24,Expense,Rnt,7335,Upi,hyderabad,Coffee
15896,T7486,U142,27-02-24,Expense,Educaton,4353,card,BANGALORE,NaN
15897,T13247,U001,03/04/2024,Expense,food,1048,CRD,BANGALORE,Train ticket
15898,T13301,U147,2022-07-09,Income,Others,621176,CARD,CHENNAI,Restaurant dinner
15899,T8679,U044,08/04/2022,Expense,Utlities,5459 INR,CARD,MUM,Gym membership

In [3]:
df.head()

,transaction_id,user_id,date,transaction_type,category,amount,payment_mode,location,notes
0,T4999,U018,2023-04-25,Expense,Educaton,3888,card,Ahmedabad,Movie tickets
1,T12828,U133,08/05/2022,Expense,rent,649,NaN,Hyderabad,asdfgh
2,T7403,U091,31-12-23,Income,Freelance,13239,Csh,BAN,Books
3,T12350,U097,NaN,Expense,Fod,6299,Bank Transfer,AHMEDABAD,Electricity bill
4,T7495,U088,10/28/2022,Expense,entertainment,2287,CARD,Hyderabad,NaN

In [4]:
df.tail()

,transaction_id,user_id,date,transaction_type,category,amount,payment_mode,location,notes
15895,T7467,U033,21-07-24,Expense,Rnt,7335,Upi,hyderabad,Coffee
15896,T7486,U142,27-02-24,Expense,Educaton,4353,card,BANGALORE,NaN
15897,T13247,U001,03/04/2024,Expense,food,1048,CRD,BANGALORE,Train ticket
15898,T13301,U147,2022-07-09,Income,Others,621176,CARD,CHENNAI,Restaurant dinner
15899,T8679,U044,08/04/2022,Expense,Utlities,5459 INR,CARD,MUM,Gym membership

In [5]:
df.shape

(15900, 9)

In [6]:
df.size

143100

In [7]:
df.info

<bound method DataFrame.info of       transaction_id user_id        date transaction_type       category  \
0              T4999    U018  2023-04-25          Expense       Educaton
1             T12828    U133  08/05/2022          Expense           rent
2              T7403    U091    31-12-23           Income      Freelance
3             T12350    U097         NaN          Expense            Fod
4              T7495    U088  10/28/2022          Expense  entertainment
...              ...     ...         ...              ...            ...
15895          T7467    U033    21-07-24          Expense            Rnt
15896          T7486    U142    27-02-24          Expense       Educaton
15897         T13247    U001  03/04/2024          Expense           food
15898         T13301    U147  2022-07-09           Income         Others
15899          T8679    U044  08/04/2022          Expense       Utlities

         amount   payment_mode   location              notes
0          3888           card  Ahmedabad      Movie tickets
1           649            NaN  Hyderabad             asdfgh
2         13239            Csh        BAN              Books
3          6299  Bank Transfer  AHMEDABAD   Electricity bill
4          2287           CARD  Hyderabad                NaN
...         ...            ...        ...                ...
15895      7335            Upi  hyderabad             Coffee
15896      4353           card  BANGALORE                NaN
15897      1048            CRD  BANGALORE       Train ticket
15898    621176           CARD    CHENNAI  Restaurant dinner
15899  5459 INR           CARD        MUM     Gym membership

[15900 rows x 9 columns]>

In [8]:
print("\nMissing values:\n", df.isnull().sum())

Missing values:
 transaction_id         0
user_id                0
date                 486
transaction_type       0
category             285
amount               291
payment_mode         808
location            1262
notes               2821
dtype: int64

In [9]:
print("\nDuplicate rows:", df.duplicated().sum())

Duplicate rows: 900

In [10]:
df = df.drop_duplicates()

In [11]:
if 'Date' in df.columns:
    df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

In [12]:
if 'Amount' in df.columns:
    df['Amount'] = (df['Amount']
                    .astype(str)
                    .str.replace('[^0-9.-]', '', regex=True)
                    .astype(float))

In [13]:
amount = df.select_dtypes(include=['float64', 'int64']).columns

In [14]:
df[amount] = df[amount].fillna(df[amount].mean())

In [15]:
cat_cols = df.select_dtypes(include=['object']).columns
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

C:\Users\user\AppData\Local\Temp\ipykernel_18256\3660225717.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].fillna(df[col].mode()[0])

In [16]:
for col in cat_cols:
    df[col] = df[col].astype(str).str.strip().str.title()

C:\Users\user\AppData\Local\Temp\ipykernel_18256\353621401.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().str.title()
C:\Users\user\AppData\Local\Temp\ipykernel_18256\353621401.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().str.title()
C:\Users\user\AppData\Local\Temp\ipykernel_18256\353621401.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().str.title()
C:\Users\user\AppData\Local\Temp\ipykernel_18256\353621401.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().str.title()
C:\Users\user\AppData\Local\Temp\ipykernel_18256\353621401.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().str.title()
C:\Users\user\AppData\Local\Temp\ipykernel_18256\353621401.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().str.title()
C:\Users\user\AppData\Local\Temp\ipykernel_18256\353621401.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().str.title()
C:\Users\user\AppData\Local\Temp\ipykernel_18256\353621401.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().str.title()
C:\Users\user\AppData\Local\Temp\ipykernel_18256\353621401.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().str.title()

In [17]:
for col in amount:
    q1, q3 = df[col].quantile([0.25, 0.75])
    iqr = q3 - q1
    lower, upper = q1 - 1.5 * iqr, q3 + 1.5 * iqr
    df[col] = np.where(df[col] < lower, np.nan, df[col])
    df[col] = np.where(df[col] > upper, np.nan, df[col])
df[amount] = df[amount].fillna(df[amount].median())

In [18]:
if 'Amount' in df.columns:
    df['Expense_Level'] = np.where(df['Amount'] > df['Amount'].median(), 'High', 'Low')

In [19]:
if 'Date' in df.columns:
    df['Month'] = df['Date'].dt.month_name()

# (c) Create a derived metric – Annualized Spending
if 'Amount' in df.columns:
    df['Annualized_Spending'] = df['Amount'] * 12

In [20]:
print("\n INSIGHT 1: Average Amount by Category ")
if 'user_id	' in df.columns:
    print(df.groupby('user_id')['Amount']
          .agg(['mean', 'sum'])
          .sort_values(by='sum', ascending=False)
          .head())

 INSIGHT 1: Average Amount by Category

In [21]:
print("\n--- INSIGHT 2: Top 5 Highest Expenses ---")
if 'Amount' in df.columns:
    print(df.sort_values('Amount', ascending=False).head(5))

--- INSIGHT 2: Top 5 Highest Expenses ---

In [22]:
print("\n--- INSIGHT 3: Most Common Payment Methods ---")
if 'Payment Method' in df.columns:
    print(df['Payment Method'].value_counts().head())

--- INSIGHT 3: Most Common Payment Methods ---

In [23]:
print("\n--- INSIGHT 3: Most Common Payment Methods ---")
if 'Payment Method' in df.columns:
    print(df['Payment Method'].value_counts().head())

--- INSIGHT 3: Most Common Payment Methods ---

In [24]:
print("\n--- INSIGHT 4: Monthly Spending by Expense Level ---")
if 'Month' in df.columns and 'Expense_Level' in df.columns:
    print(pd.pivot_table(df, values='Amount', index='Month', columns='Expense_Level', aggfunc='sum'))

--- INSIGHT 4: Monthly Spending by Expense Level ---

In [25]:
print("\n--- INSIGHT 5: Transactions Above Average Spending ---")
if 'Amount' in df.columns:
    avg_amt = df['Amount'].mean()
    print(df[df['Amount'] > avg_amt][['Category', 'Amount']].head())

--- INSIGHT 5: Transactions Above Average Spending ---

In [26]:
print("\nFinal shape:", df.shape)
print("\nCleaned dataset preview:\n", df.head())

Final shape: (15000, 9)

Cleaned dataset preview:
   transaction_id user_id        date transaction_type       category amount  \
0          T4999    U018  2023-04-25          Expense       Educaton   3888
1         T12828    U133  08/05/2022          Expense           Rent    649
2          T7403    U091    31-12-23           Income      Freelance  13239
3         T12350    U097  2024-08-13          Expense            Fod   6299
4          T7495    U088  10/28/2022          Expense  Entertainment   2287

    payment_mode   location             notes
0           Card  Ahmedabad     Movie Tickets
1            Upi  Hyderabad            Asdfgh
2            Csh        Ban             Books
3  Bank Transfer  Ahmedabad  Electricity Bill
4           Card  Hyderabad  Electricity Bill

In [27]:
df

,transaction_id,user_id,date,transaction_type,category,amount,payment_mode,location,notes
0,T4999,U018,2023-04-25,Expense,Educaton,3888,Card,Ahmedabad,Movie Tickets
1,T12828,U133,08/05/2022,Expense,Rent,649,Upi,Hyderabad,Asdfgh
2,T7403,U091,31-12-23,Income,Freelance,13239,Csh,Ban,Books
3,T12350,U097,2024-08-13,Expense,Fod,6299,Bank Transfer,Ahmedabad,Electricity Bill
4,T7495,U088,10/28/2022,Expense,Entertainment,2287,Card,Hyderabad,Electricity Bill
...,...,...,...,...,...,...,...,...,...
15894,T13908,U113,21-02-2023,Expense,Fod,$9952,Upi,Luc,Electricity Bill
15895,T7467,U033,21-07-24,Expense,Rnt,7335,Upi,Hyderabad,Coffee
15896,T7486,U142,27-02-24,Expense,Educaton,4353,Card,Bangalore,Electricity Bill
15897,T13247,U001,03/04/2024,Expense,Food,1048,Crd,Bangalore,Train Ticket
15899,T8679,U044,08/04/2022,Expense,Utlities,5459 Inr,Card,Mum,Gym Membership